require('options')

-- Initialize plugins
require("oil").setup()
require("telescope").setup()
require("typst-preview").setup()

-- User config
require('config/themes/catppuccin')
require('config/themes/gruvbox')
require('config/themes/gruvbox-baby')
require('config/treesitter')
require('config/lsp')
require('config/lualine')
require('config/presence')
require('config/autopairs')
require('config/autotag')
require('config/harpoon')
require('config/neoscroll')
require('config/gitsigns')
require('config/dashboard')
require('config/ibl')
require('config/vimtex')
require('config/themery')
require('config/cmp')
require('config/obsidian')
require("config/render-markdown")
require("config/snacks")
require("config/avante")
require("config/copilot")

vim.keymap.set("i", "<C-t>", function()
  local time = os.date("%H:%M")
  vim.api.nvim_put({ "## " .. time }, "c", true, true)
end, { desc = "Insert current time" })
